### ISSUE TITLE
written_questions have all kinds of weird chars for accented chars

### ISSUE THREAD

**Issue by philippeback** [Psycojoker/dierentheater#11]
I loaded the json back into mongodb and it is dirty there too.

Could this be linked to pdf2text not doing its job properly?

e.g. direclty copied from a record in Robomongo:

{
    "_id" : ObjectId("53741f7c3e499606271b51f0"),
    "departement" : {
        "fr" : " Ministre de l'Int�rieur",
        "nl" : " Minister van Binnenlandse Zaken"
    },
    "keywords" : {
        "fr" : [],
        "nl" : []
    },
    "eurovoc_descriptors" : {
        "fr" : [ 
            "DESASTRE NATUREL, DOMMAGES ET INTERETS, INONDATION"
        ],
        "nl" : [ 
            "NATUURRAMP, SCHADEVERGOEDING, OVERSTROMING"
        ]
    },
    "publication_question_pdf_url" : "/QRVA/pdf/50/50K0001.pdf",
    "publication_reponse_pdf_url" : "/QRVA/pdf/50/50K0018.pdf",
    "author" : " Jan Mortelmans, VB",
    "question" : {
        "fr" : "<td>\n\n\t\t\n\t\t\t\t<p> Les inondations du mois de septembre de l'ann�e derni�re ont frapp�\ndes milliers de familles.\n1. Pourriez-vous me faire savoir combien de dossiers ont en\nd�finitive �t� introduits (par province) au lendemain des inondations\nde l'ann�e derni�re?\n2. Quelle suite y a �t� r�serv�e � ce jour?\n3. Pourriez-vous aussi me dire dans combien de cas un expert de la\nprovince s'est rendu sur place et dans combien de dossiers une\ncontre-proposition a �t� formul�e par la province (par province)?\n4. Pourriez-vous pr�ciser le nombre de dossiers d'indemnisation qui\nont d�j� �t� trait�s ainsi que le rapport entre les d�g�ts subis et\nl'indemnisation accord�e?\n5. A combien s'�l�veront globalement les indemnisations vers�es par\nle Fonds des calamit�s?</p> \n\t\t\t\n\t\t<font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"+0\">  </font>\n\t</td>",
        "nl" : "<td>\n\n\t\t\n\t\t\t\t<p> De watersnood heeft in september vorig jaar duizenden gezinnen\ngetroffen.\n1. Kan u meedelen, opgesplitst per provincie, hoeveel dossiers\nuiteindelijk werden ingediend na de wateroverlast vorig jaar?\n2. Wat is het gevolg dat hieraan tot op heden werd gegeven?\n3. Kan u ook meedelen - eveneens opgesplitst per provincie - in\nhoeveel gevallen een expert van de provincie is langsgekomen en bij\nhoeveel van de dossiers een tegenvoorstel door de provincie werd\ngedaan?\n4. Kan u meedelen hoeveel dossiers reeds werden uitbetaald en wat de\nverhouding is tussen de opgegeven schade en de toegekende\nschadevergoeding?\n5. Hoeveel zal het Rampenfonds uiteindelijk in totaal hebben\nuitgekeerd?</p>\n\t\t\t\n\t\t<font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"+0\">  </font>\n\t</td>"
    },
    "current" : true,
    "question_status" : {
        "fr" : "R�ponses re�ues ",
        "nl" : "Antwoorden ontvangen"
    },
    "answer" : {
        "fr" : "\n\t\t\t\t\t \n\t\t\t\t\t La question de l'honorable membre a �t� transmise au ministre de la\nMobilit� et des Transports qui est comp�tent en la mati�re. (Question\nno 121 du 9 f�vrier 2000.)\n\t\t\t\t\t \n\t\t\t\t",
        "nl" : "\n\t\t\t\t\t \n\t\t\t\t\t De vraag van het geachte lid werd overgemaakt aan de minister van\nMobiliteit en Vervoer die terzake bevoegd is. (Vraag nr. 121 van 9\nfebruari 2000.)\n\t\t\t\t\t \n\t\t\t\t"
    },
    "eurovoc_candidats_descriptors" : {
        "fr" : [],
        "nl" : []
    },
    "status" : {
        "fr" : "",
        "nl" : ""
    },
    "creation_datetime" : ISODate("2014-05-15T03:59:24.005Z"),
    "publication_question" : "\n\t\t\t   \n\t\t\tB001\n\t\t\t- Page : 13",
    "publication_reponse" : "\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t     \n\t\t\t\t\t\t\tB018  - Page : 1955 \t\t\t\t\t\t\n\t\t\t\t\t\t",
    "delay_date" : "",
    "publication_date" : "14/02/2000, 199920000",
    "sub_departement" : {
        "fr" : " Int�rieur",
        "nl" : " Binnenlandse Zaken"
    },
    "lachambre_id" : "50-b018-11-0002-0000199950015",
    "language" : " N",
    "url" : "showpage.cfm?section=qrva&language=fr&cfm=qrvaXml.cfm?legislat=50&dossierID=50-b018-11-0002-0000199950015.xml",
    "title" : {
        "fr" : " Inondations. - Dossiers. - Indemnisations.",
        "nl" : " Watersnood. - Dossiers. - Schadevergoedingen."
    },
    "deposition_date" : "29/07/1999"
}

**Comment by Psycojoker** [comment]
Fixed. Thanks for reporting :)

**Comment by philippeback** [comment]
Thx for the fix. Ah, let's hope I get a moment to load the whole thing now.
